feat: add i18n dictionary
Rabbittee/body-composition pull request #47
Opened 2022-08-18 13:54 UTC by haha861924

# CHANGES

- [x] i18n dictionary
- [ ]  set i18n

2022-08-25 01:31 UTC, HuskyHsu commented on src/locales/zhTW.json
> +    "waistAndHight": "腰身高比",
```suggestion
    "waistAndHight": "腰圍身高比",
```

2022-08-25 01:47 UTC, HuskyHsu commented on src/locales/zhTW.json
> +    "basalMetabolism": "基礎代謝率",
```suggestion
    "basalMetabolism": "基礎代謝率(仟卡)",
```

2022-08-25 01:47 UTC, HuskyHsu commented on src/locales/zhTW.json
> +    "tdee": "TDEE"
```suggestion
    "tdee": "TDEE(仟卡)"
```

2022-08-25 01:47 UTC, HuskyHsu commented on src/locales/zhTW.json
> +    "dailyHeatSuggest" : "每日熱量攝取建議",
```suggestion
    "dailyHeatSuggest" : "每日熱量攝取建議(仟卡)",
```

2022-08-25 01:47 UTC, HuskyHsu commented on src/locales/en.json
> +    "dailyHeatSuggest" : "Daily Heat Suggest",
```suggestion
    "dailyHeatSuggest" : "Daily Heat Suggest(kcal)",
```

2022-08-25 01:47 UTC, HuskyHsu commented on src/locales/en.json
> +    "tdee": "TDEE"
```suggestion
    "tdee": "TDEE(kcal)"
```

2022-08-25 01:47 UTC, HuskyHsu commented on src/locales/en.json
> +    "basalMetabolism": "Basal Metabolic Rate",
```suggestion
    "basalMetabolism": "Basal Metabolic Rate(kcal)",
```

2022-08-25 01:51 UTC, HuskyHsu commented on src/locales/en.json
> +    "scarcely":"Scarcely",
prettier not work or pass json file?

2022-08-25 02:00 UTC, ashramwen requested changes

2022-08-26 02:55 UTC, haha861924 commented on src/locales/zhTW.json
> +    "waistAndHight": "根據活動量及最低BMR計算",
![image](https://user-images.githubusercontent.com/40877568/186806492-5bdc83c4-5552-4bc8-9464-809c2b68dfc5.png)
![image](https://user-images.githubusercontent.com/40877568/186806521-30f0a883-c23c-447f-b8f6-0d623495104a.png)

應該是只需要一個

2022-09-06 08:20 UTC, ashramwen approved these changes

2022-09-06 08:20 UTC, merged